matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      cache:
        directories:
          - "node_modules"
      before_script:
        - npm install -g @angular/cli
      script:
        - ng lint
        - ng build --prod --base-href $base_href


    - language: csharp
      mono: none
      dist: xenial
      sudo: required
      dotnet: 3.1.201
      branches:
        only:
          - master
      script:
        - dotnet restore TurtleCMS
        - dotnet build TurtleCMS
notifications:
  email: false