matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      cache:
        directories:
          - "node_modules"
      before_script:
        - npm install -g @angular/cli
      script:
        - ng lint --base-href TurtleCMS/ClientApp
        - ng build --prod --base-href TurtleCMS/ClientApp


    - language: csharp
      mono: none
      dist: xenial
      sudo: required
      dotnet: 3.1.201
      branches:
        only:
          - master
      script:
        - dotnet restore TurtleCMS
        - dotnet build TurtleCMS
notifications:
  email: false